version: '3.0'
services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 端口映射
      - "13306:3306"
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '16379:6379'
  etcd:
    image: 'bitnami/etcd'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - '12379:2379'
  mongo:
    image: 'mongo:6.0'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017